# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ruben Taelman
email: example@example.com
description: > # this means to ignore newlines until "baseurl:"
  Computer scientist, researcher, programmer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rubensworks.net" # the base hostname & protocol for your site
twitter_username:       rubensworks
github_username:        rubensworks
linkedin_username:      taelmanruben
googleplus_username:    111756755066956993602
googlescholar_username: 2avKLOkAAAAJ
google_analytics_tracking_id : 'UA-4197493-1'
permalink: pretty

# Build settings
markdown: kramdown

# Publication settings
scholar:
  sort_by: year,month
  order: descending
  bibliography_template: bib
  details_dir: publications
  details_layout: bibtex.html
  details_link: More
  bibtex_skip_fields:
    - abstract
    - month_numeric
    - _type
    - _slides
    - _poster

exclude:
  - script
  - Gemfile
  - README.md
  - Rakefile
  - vendor

collections:
  projects:
    output: true
